baseURL = "/"
languageCode = "en-us"
title = "I Smorzisti S.r.l. - Materiali edili, ferramenta, accessori da lavoro"
theme = "smorzi"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Chi siamo"
    url = "/chi-siamo/"
    weight = 2
  [[menu.main]]
    name = "Prodotti"
    url = "/prodotti/"
    weight = 3
  [[menu.main]]
    name = "Servizi"
    url = "/servizi/"
    weight = 3
  [[menu.main]]
    name = "Articoli"
    url = "/posts/"
    weight = 4
  [[menu.main]]
    name = "Contattaci"
    url = "/contattaci/"
    weight = 5
